kind: Deployment
apiVersion: apps/v1
metadata:
  name: insights-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insights-service-app
  template:
    metadata:
      labels:
        app: insights-service-app
    spec:
      containers:
        - name: insights-service
          image: insights-service-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: insights-service
spec:
ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
selector:
  app: insights-service-app
